### ISSUE TITLE
Add class "is-valid"

### ISSUE THREAD

**Issue by belial-dev** [1000hz/bootstrap-validator#141]
Hi,

I try to apply a class to the group when a field becomes valid like "is-valid",

Thank you in advance,

**Comment by 1000hz** [comment]
This is kind of tricky to do because a form field can be valid by default. The validator will already add `.has-error` when a field becomes invalid. You could instead use the selector `:not(.has-error)`.

Alternatively, you can bind to the `valid.bs.validator`/`invalid.bs.validator` events to add/remove an `is-valid` class.
