### ISSUE TITLE
Two errors displayed at a time on form validation

### ISSUE THREAD

**Issue by sunnyprakash** [1000hz/bootstrap-validator#173]
Hi,
I am trying to execute below code.
\<input type="text" class="form-control" id="empid" name="empid"
data-minlength="4" maxlength="20" data-minlength-error="Minimum 4 characters required"
pattern="^([A-Za-z0-9]{1,}[a-zA-Z0-9.!@()-_`~]{0,}[A-Za-z0-9]{1,}){1,}$" 
placeholder="EMP ID"
data-error="EMP ID is invalid" required>

In some cases, it gives both error i.e data-minlength-error and data-error in \<div class="help-block with-errors"></div> by listing \<li>. How can we restrict to show only one error i.e data-error ?

**Comment by 1000hz** [comment]
Sorry, this isn't possible. If only the minlength validator was failing, you'd get just the one message, but since the field is failing for multiple reasons, it's showing both error messages. The only thing you can really do is get rid of the custom error for minlength or get rid of your blanket data-error message. The browser has built-in defaults for the different kind of validations ("Please match the request format for the pattern validator, or "This field is required" for the required validator) so it will still show multiple error messages, but they'll at least be more relevant to the user.
