### ISSUE TITLE
Integrate boostrap-validator with chosen jQuery plugin

### ISSUE THREAD

**Issue by massbath** [1000hz/bootstrap-validator#193]
Hello,

I'am using your library with different forms. In parallel I also employ chosen jQuery plugin v1.1.0 for my selects, there is a way to validate fields like this with your library ?

**Comment by krissenden** [comment]
also with the bootstrap-select plugin it is not working...

**Comment by massbath** [comment]
Ok, no solution until now ?

**Comment by mikestecker** [comment]
Would also like to use with [Selectize.js](http://brianreavis.github.io/selectize.js/) I found an example of using a different validation script with Selectize but I'd like to use this bootstrap validator.

**Comment by nicocarolo** [comment]
Hi, anyone can solve it? i want to use a multiple select but i can not validate, thanks.

**Comment by MaartenGregoire** [comment]
Adding this just after loading the validator script worked for me:
$.fn.validator.Constructor.INPUT_SELECTOR = ':input:not([type="submit"], button):enabled';

**Comment by dario86** [comment]
Same problem with selectize...

**Comment by 1000hz** [comment]
invisible elements are no longer ignored by the validator in v0.11.0

**Comment by bhartvigsen** [comment]
This still isn't perfect. For some reason it works on an initial pageload, but then subsequently refreshing the page causes validation errors to not populate. The validation itself still works, just the errors fail to appear. I'm having to put a 500ms setTimeout around all my chosen elements in order to get validation to work.
