### ISSUE TITLE
Is there protection against someone using inspect element to remove required attribute from elements?

### ISSUE THREAD

**Issue by aguerrero810** [1000hz/bootstrap-validator#194]
When i tried it on my local webserver i was able to remove the 'required' attribute from elements and submit the form without having to fill anything out. is this just me not doing something or can it be prevented?

**Comment by 1000hz** [comment]
No, but you shouldn't rely on this plugin or any client-side code as the only guarantee of the validity of your data. You still need to validate the data on the server because that's the only way you can be sure your validity checks haven't been bypassed. Client-side validation should only be used as a means to improve user experience and give more immediate feedback to the user. Even if you were to somehow guarantee that users couldn't modify your form, there's nothing stopping them from sending a direct http POST to your server with invalid data.

**Comment by aguerrero810** [comment]
i see. i'm sorta new at web development so thanks for the insight!

**Comment by 1000hz** [comment]
No worries. Always glad to help!
