### ISSUE TITLE
No way to validate a single field on command?

### ISSUE THREAD

**Issue by dangnelson** [1000hz/bootstrap-validator#197]
I want to run a function that talks to an API and gives back a value.

Based on the value I want to validate / invalidate the field.

Is there any way to validate a single field on command without having to validate the entire form?

Maybe I'm missing something in the docs?

**Comment by 1000hz** [comment]
It sounds like you might be able to use [the `remote` validator](http://1000hz.github.io/bootstrap-validator/#validator-markup) to do what you need.

To answer your original question, you can validate a single field by triggering an `input` event on it
```js
$('#myField').trigger('input')
```

**Comment by gbreeze** [comment]
not working on v0.10.2, worked on v0.9.x

**Comment by 1000hz** [comment]
Can you elaborate on the issue @gbreeze?

**Comment by Jargon64** [comment]
I've been struggling getting the triggering of input events to re-run validation on single fields as well. Currently running version 0.10.01. Are we sure this isn't broken now?

**Comment by Jargon64** [comment]
After doing a bit of testing, it appears that using an input event trigger to revalidate a field just makes it use the previous cached validation results as the field values haven't actually changed. This means you can't act on (or present) any server side errors thrown after submitting the form because the form is already considered valid and no values have changed to invalidate the cache.

**Comment by xxRockOnxx** [comment]
> $('#myField').trigger('input')

+1 on this. I've been looking for a way to do this and this really works! I thought .validator('update') is supposed to be used on this purpose. The trigger input is the answer.

**Comment by 1000hz** [comment]
also, you can use `$('#myField').trigger('focusout')` instead to immediately display the error without waiting for the delay period to complete.
