### ISSUE TITLE
data-pattern-error has no effect

### ISSUE THREAD

**Issue by duanefields** [1000hz/bootstrap-validator#210]
From the docs, it seems like I should be able to use the `data-pattern-error` attribute to customize the error message when a `pattern` match fails. The generic `data-error` does work, but of course that effects all validators. The default message for a pattern match (Please match the requested format) appears to come from the browser itself. Would be good to override this if possible.

**Comment by 1000hz** [comment]
All of the built-in validators need `data-native-error="Your error here"` due to the way the plugin piggybacks off of the browser's validators. Unfortunately this means you can't deal with specific error messages for multiple built-in validators on the same field, but the only way around it is to reimplement all of these validators individually in the plugin which I'm hesitant to do because of the bloat it would add.
