### ISSUE TITLE
e.isDefaultPrevented returning false after destroy + recreate

### ISSUE THREAD

**Issue by nezoic** [1000hz/bootstrap-validator#244]
I'm not entirely certain this is a bug, but it appears that after $().validator('destroy'), if you attempt to re register the form validation again it no longer works. or at least e.isDefaultPrevented always false, yet I see the validations on the screen but the form can still be submitted.

**Comment by toxidev** [comment]
I faced with same issue

**Comment by fernandobeltranjsc** [comment]
Same problem here, in single page applications it's a big problem :(

**Comment by 1000hz** [comment]
You will need to rebind your event handler that checks `e.isDefaultPrevented()` after you destroy/reinit the validator because the `e.isDefaultPrevented()` check needs to run after the validator. Since jQuery runs event handlers in the order they are bound, it's now happening before the validator has a chance to run.
