### ISSUE TITLE
Manually test if form is valid

### ISSUE THREAD

**Issue by jeroenooms** [1000hz/bootstrap-validator#247]
Is there a method to test if a form is completely valid without actually submitting it? I'd like to display some meta information on which forms within the page are 'ready'.

**Comment by 1000hz** [comment]
You can call `$('#myForm').validator('validate')`, but that will show any errors on invalid fields. Not sure if you want more of a silent validation, which is not possible.

**Comment by jeroenooms** [comment]
It doesn't have to be silent, I just want to know the outcome.

**Comment by 1000hz** [comment]
Then I think you can probably do

```js
if ($('#myForm').validator('validate').has('.has-error')) {
  ...
}
```

**Comment by jeroenooms** [comment]
OK i'll try that. You should really consider making a method for this, it's useful to be able to programmatically test if the form is valid (rather than just visually)

**Comment by bhartvigsen** [comment]
That above method does work, but you really ought to have a method call for checking validity of the form. I was using your submit() technique along with isDefaultPrevented, and while it worked on 99% of all browsers, it caused certain iOS Safari versions to break my app because it was submitting the form rather than allowing the preventDefault from occuring. Since I populate my ACTUAL form data with JS, it was posting the wrong (and incomplete) data.

**Comment by 1000hz** [comment]
I know. Once I get custom validators integrated with HTML5's `Element.setCustomValidity()` then you'll be able to use `FormElement.checkValidity()`.

**Comment by bhartvigsen** [comment]
Awesome, thanks. Great validator btw.
