### ISSUE TITLE
How to perform min length plus remote validation - for example checking a username field for uniqueness?

### ISSUE THREAD

**Issue by sunitk** [1000hz/bootstrap-validator#255]
Maybe I am missing something from the documentation.

**Use Case: Username field must be x characters long and should be unique**

The use case is that a username field must be validated first for certain minimum length (or any of the standard client side validation).

After this validation check passes, the next validation is to query the server for uniqueness of the value entered in the username field. I have followed your [remote validation example](https://github.com/1000hz/validator-remote-example) but when I use that technique, the error message that "Username not unique" i.e. the server response starts getting shown even when user types a couple of letters. I would like the remote validation to fire after the user has stopped typing or has tabbed out. Also the validation for min. length should happen prior to the remote validation.

Can you please point to an example or sample code on how this can be achieved?

This facility exists in [jQueryValidation](http://jqueryvalidation.org). It would be really convenient to have it in this plugin.

Thank you.

**Comment by 1000hz** [comment]
The remote validator won't run if there are any other errors on the field. Try it out here:
http://jsbin.com/fivocazero/edit?html,css,js,output

Open up the dev tools and see that the remote request is only sent after you've typed in at least 6 characters.


Are you sure you're using `data-minlength` instead of mistakenly just `minlength`?
