### ISSUE TITLE
disabled class removed when form is contained in a Bootstrap modal Not Working Solution

### ISSUE THREAD

**Issue by mohamadbadrian** [1000hz/bootstrap-validator#276]
hi dear cina
[https://github.com/1000hz/bootstrap-validator/issues/220](url)
i have the same problem but the solution that you say is not for this problem . when i use a form with validator in simple way , the submit button take disabled class in the first , but when i use this form in a bootstrap modal the submit button disabled class is remove when the modal show and in the first run submit button is active , when the focus of element changed , the submit button disabled again ! 
this bug convert to serious issue when use it with ajax together , is any solution for that?

thanks

**Comment by 1000hz** [comment]
In the code solution for that issue, I accidentally put the wrong namespace for the `shown`/`hidden` events (`.bs.validator` instead of `.bs.modal`). I've edited the code to clear up further confusion, but here it is again:

```js
$('#myModal')
  .on('shown.bs.modal', function (e) {
    $('#myForm').validator()
  })
  .on('hidden.bs.modal', function (e) {
    $('#myForm').validator('destroy')
  })
```

Here's a demo of it working:
http://jsbin.com/dubodaniha/edit?html,js,output

**Comment by mohamadbadrian** [comment]
ok i seen your post before but this solution cant solve the problem , i manually add this to your code

`$('#myModal')
  .on('shown.bs.modal', function (e) {
    $('#myForm').validator()
    $('#btnsubmit').addClass("disabled");
  })
  .on('hidden.bs.modal', function (e) {
    $('#myForm').validator('destroy')
  })`

**Comment by 1000hz** [comment]
If you can reproduce the issue on JSBin I might be able to help further, but I don't have enough of an understanding of your problem right now to give you more information.

**Comment by tcrisafulli** [comment]
I know this issue is close but I have run into the same issue.  When the form is used in a bootstrap modal window the submit button does not work correctly.  The submit button is not disabled by default.  Manually disabling the button like the code above only works if there is a single required field, as soon as I type in one valid field the button becomes enabled even though there are other required fields with no data.

**Comment by 1000hz** [comment]
Sorry, I can't help you without a JSBin reproducing the issue.

**Comment by tcrisafulli** [comment]
Found the issue - I had role="form" in the form tag.  I was refactoring this to from a form in aspx page where I was using a div tag to get around the nested form issue in WebForms.  But created a form tag once it was loading into a modal window that was outside the existing webform "form" tag.
