### ISSUE TITLE
trigger maxlength validation error

### ISSUE THREAD

**Issue by samerdev** [1000hz/bootstrap-validator#279]
I have this input field
`<input type="text" name="name1" id="name1" maxlength="10">`
I'm loading data to this field using:
`$("#name1").val("Data with length more than 10")`
It's not showing any error, I tried to do this after setting the field value:
`$("#name1").trigger("input")`
And also no error.
The only way to validate the field is to try to edit the field directly
Also, I tried to do simulate spacebar keypress
http://stackoverflow.com/questions/1468384/simulate-keypress-with-jquery
any suggestion?

**Comment by 1000hz** [comment]
There isn't actually a maxlength validator because the browser just prevents the user from typing in more than _n_ characters. In your case since you're programmatically setting the value you'd need to add a custom validator for maxlength.

```js
$('#myForm').validator({
  custom: {
    'maxlength': function ($el) {
      var maxlength = $el.data('maxlength')
      return !$el.val() || $el.val().length <= maxlength
    }
  },
  errors: {
    'maxlength': "Too long"
  }
})
```
```html
<input type="text" name="name1" id="name1" maxlength="10">
```

Or you could just truncate the value to 10 characters when you set it on the field and the user won't be able to input past that.

**Comment by samerdev** [comment]
it's working great.
I just named the new custom function 'maxcheck' and kept the  'maxlength' attribute:
`<input type="text" name="name1" id="name1" data-maxcheck="maxcheck" maxlength="10">`
I'm receiving now two error messages and for me there's no problem with that.

Thanks you,
Sam
