### ISSUE TITLE
issue with data-disable on form button

### ISSUE THREAD

**Issue by robgaleano** [1000hz/bootstrap-validator#294]
Hello, i can't seem to find a way for this function to work, i don't know why, i've already added the required property to every single input in the form, and tried also by adding the data-disable="true" on the form tag. Here's my code in this zip:
[comprar.php.zip](https://github.com/1000hz/bootstrap-validator/files/176819/comprar.php.zip) 
Any suggestions??

**Comment by stephendidit** [comment]
I added the class "disabled" to the button, and on page load the class is still present, but after about a second, the "disabled" class is removed, --at the same moment that novalidate="true" is added to the form.

**Comment by stephendidit** [comment]
Okay...here's my workaround. On the button you need to disable, add `disabled="disabled" ` and then you can use this to deal with the form validation:
```
$( "form" ).on( "valid.bs.validator", function() {
  $( "#subscribe_submit " ).prop("disabled", false);
});
```
I couldn't make it work with the 'disabled' class, because it kept removing it, even when I removed the lines in the validator.js that seemed to be responsible for it! Good luck--

**Comment by 1000hz** [comment]
@robgaleano: My guess is that the validator was ignoring your input fields because they weren't visible on the page when the plugin was initialized. This behavior has changed in v0.11.x of the plugin.

@stephendidit: `novalidate` is added to prevent the browser's default constraint validation dialogs from appearing. The `disabled` property is intentionally not used (the validator sets `.disabled` as a class) and shouldn't be added manually. The reason a class is used instead of the property is to allow the user to attempt to submit (via hitting enter or clicking the button) which reveals the invalid fields and error messages.
