### ISSUE TITLE
Cancel button starts validation for form

### ISSUE THREAD

**Issue by BWeesy** [1000hz/bootstrap-validator#320]
I have a required text field, a submit button (type = "submit"), and a cancel button (type = "button").
Starting from a pristine form, if I focus on the text field and then click the cancel button, the cancel method is blocked by the form validation starting.

Is there any way to stop the cancel button firing the validation for the entire form?

For clarification, the cancel works fine if the validation has already begun (the focus changed from the input or the user started typing or what-have-you).

Cheers

**Comment by 1000hz** [comment]
Can you put an example on JSBin? I don't really understand your issue.
http://jsbin.com/vemasezaki/1/edit?html,css,js,output

**Comment by ss44** [comment]
I found that this is also replicated with any links on a page which also has the validator attached to a form.

http://jsbin.com/yuwubuvuki/edit?html,css,js

**Expected Behaviour**: Clicking the cancel link or (button) would perform the cancel action i.e navigate away from the page.

**Current Behaviour**: Clicking the cancel link triggers the focusout action which blocks the links default event from triggering. Leading you to need to wait for validation to complete and then click the link to successfully navigate away from the form.

**Comment by 1000hz** [comment]
In your example, the link to google isn't working because of iframe security issues, not because of the validator.

`Refused to display 'https://www.google.com/?gws_rd=ssl' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

**Comment by ss44** [comment]
@1000hz - Give this link a try, it's out of the iFrame.

http://jsbin.com/mitokin/1

I included an attached screen grab demonstrating the issue. I initially refresh the page after load. The first click causes the focusout event to trigger and prevents the actual links action from being triggered. Clicking a second time forwards on to google.

http://quick.as/4Z07SA0m0

**Comment by 1000hz** [comment]
In that case, the link is just being pushed out of the way. The browser isn't registering it as a "click" because mouseup isn't happening on it. You can see that's what is happening if you click and hold the cancel button, then move your mouse back over the link before you release the mouse button.

There's not really a good fix for that.

**Comment by ss44** [comment]
@1000hz Thanks for your insight, confirmed that was the case by adding styling the div to not get in the way. Looks like an easy styling fix will resolve my issue. 

Thanks for your help.

**Comment by rsshilli** [comment]
I'm having the same issue.  @ss44 What kind of styling did you add to work around this issue?

Also, why is it closed?  I don't see any reason why the validator should get in the way of other links outside of the form.

**Comment by ss44** [comment]
@rsshilli In my case I added a fixed height for where the error messages were going to appear so that the page or fields weren't pushed in any way if they did happen to show up.

**Comment by rsshilli** [comment]
Ah!  I get it.  For the next person, I added the following and that fixed it:
 
.help-block {
    height: 20px;
}

.form-group {
    margin-bottom: 0px;
}
