### ISSUE TITLE
Not Working with Bootstrap modal

### ISSUE THREAD

**Issue by monski** [1000hz/bootstrap-validator#345]
Not Working with Bootstrap modal

**Comment by solugebefola** [comment]
I discovered that the problem for me was the `Validator.INPUT_SELECTOR` constant that is used to find the relevant DOM elements in the form.  It is set to `':input:not([type="submit"], button):enabled:visible'`, but for some reason, the inputs don't register as visible in the modal.  When I changed it to `':input:enabled:not([type="submit"], button)'` I was able to get proper validation.

**Comment by 1000hz** [comment]
It's because of an issue with caching the jQuery selection for performance boosts. They aren't visible when the plugin is being initialized.

You can either initialize the validator on the modal shown event or revert to v0.9.x of the plugin. Sorry about that, it'll get fixed in the next release (not immediately soon).

**Comment by monski** [comment]
lol, sorry also for the comment for not being polite, apologise master :) 
i like this plugin, it saves me time for doing my own...

**Comment by nelson6e65** [comment]
:persevere:
