### ISSUE TITLE
novalidate property ignored?

### ISSUE THREAD

**Issue by screenager** [1000hz/bootstrap-validator#366]
Shouldn't the validation be ignored when "novalidate" property is true on the form element?

**Comment by 1000hz** [comment]
The browser's built-in validator UI will be ignored. It doesn't stop the plugin's validator from running.

Feel free to reopen this ticket with an example if you find that not to be the case.

**Comment by dburt** [comment]
@1000hz, I agree with @screenager. The "novalidate" property is the semantic way to say, "this form should not be validated" and so bootstrap-validator should not validate such forms or fields by default.

Can we reopen this issue? Will you accept a pull request to change this?

**Comment by 1000hz** [comment]
No, we have to set `novalidate="true"` or else the browser's built-in UI will show up when the user submits the form. If you want to disable validation, you should destroy the validator instance.

**Comment by dburt** [comment]
I understand how the novalidate attribute is manipulated by the plugin on initialization and destruction of the validator instance, but @screenager is still right. My proposal is to respect the user-set value of novalidate. It can be done like this:

* on initialization, read the initial value of novalidate (set by user) and save it, before setting novalidate to true to prevent browser default validation
* on destroy, reset novalidate to what was originally set by user
* treat user-set [novalidate] fields and fields in [novalidate] forms the same as [data-validate="false"] fields by default, unless [data-validate] is set one way or the other.

**Comment by 1000hz** [comment]
Can you elaborate on why you want this functionality? Are you using `novalidate` for something? As far as your third bullet point, `novalidate` isn't a standard attribute on InputElements.

**Comment by dburt** [comment]
The reason I want this functionality is because I think it's the correct thing to do. By specifying `novalidate` the user has flagged their intention that the form not be validated.

The background is that I've dropped the plugin in onto some existing forms, and expected it to 'just work,' which it does very well, except in this situation where I've got email fields in a form which I don't want to be validated. (I want the email keyboards on mobile, but I also want to allow non-email inputs for certain cases.)

Please ignore my error on `novalidate` for inputs. There's apparently `formnovalidate` but it seems a bit unclear and I don't need it myself.

**Comment by dburt** [comment]
The reason I want this functionality is because I think it's the correct thing to do. By specifying `novalidate` the user has flagged their intention that the form not be validated.

The background is that I've dropped the plugin in onto some existing forms, and expected it to 'just work,' which it does very well, except in this situation where I've got email fields in a form which I don't want to be validated. (I want the email keyboards on mobile, but I also want to allow non-email inputs for certain cases.)

Please ignore my error on `novalidate` for inputs. There's apparently `formnovalidate` but it seems a bit unclear and I don't need it myself.

**Comment by 1000hz** [comment]
I get what you mean, but presumably if someone didn't want their form validated they wouldn't be using this plugin? I'm trying to understand a use-case in which someone would want to use this plugin and also set `novalidate` manually. Seems kind of esoteric, but yes, "correct".

The plugin doesn't use `novalidate`, nor could it because it has to be set to true or else the browser will clash with the plugin. So it wouldn't really help you in your scenario if the plugin restored its value on destroy. I'd recommend using `data-validate="false"` on your email fields, but then you'd lose any other validations like `required` as well. There's no way to turn off only `type="email"` validation.

**Comment by dburt** [comment]
Sites have more than one form. Out of all the forms in my site, most work fine and are enhanced by the plugin based on their pre-existing, standard markup. It works as a drop-in enhancement, except for this one form attribute that is not respected.

The plugin unsets `novalidate` of course, because it replaces the built-in validation. That's fine, it's how it has to work. My suggestion is to take note of the user-set value on construction of the Validator (maybe just set `data-validate` if it's not set already) before clobbering `novalidate` (line 70).

My second dot-point suggesting that the value be restored on destroy is the least important of the three, and is just basic clean-up: leave things how you found them (i.e. don't leave `novalidate` off if it was on initially).

I am using `data-validate="false"` as a workaround, which works fine. I don't need more specific validation control.

I'm still willing to work on a proper fix, respecting the standard `novalidate` attribute. You seem to have agreed my suggestion is "correct." Would you accept a pull request along the lines we've outlined?

**Comment by dburt** [comment]
@1000hz I see that I have missed something obvious, sorry for wasting your time.

The validation needs to be enabled specifically, and I had a script that was being too generous in picking which forms to add validation to.

So your point that you don't use the plugin is valid and solves the problem -- the correct solution is simply not to enable the plugin on forms you don't want it on.
