### ISSUE TITLE
data-remote response

### ISSUE THREAD

**Issue by darknest** [1000hz/bootstrap-validator#388]
Hello, not really an Issue, anyway. I'm posting this because using google didn't found nothing. I wanted to know If we could use another code for invalid field using data-remote="path". Asking this because I don't really like to have the 4xx message in the console. If that's not possible, it doesn't matter. Thanks anyway. Last thing is that I can't pass the text to the "help-block with-errors" div. Basically I send a header like this **header("HTTP/1.1 400 Text");** But can't make it use the Text in the div. Any idea?

**Comment by 1000hz** [comment]
`4xx` is the only way the `data-remote` validator distinguishes an error. It was the simplest and most flexible way I could design that feature without tying it to a specific framework or error object structure.

As far as getting the error message to show up properly, I'm not sure how you do it with your server framework, but you need to send the error as the response status message (which it seems to me like you're doing...). In the future I plan on changing that to use the response body instead of the status message since that's more reliable and a better place for content anyways.

Also the next big feature I plan on adding is being able to return promises in custom validators, so you could write your own custom validator that makes an ajax request instead of using `data-remote`.  The rules for what counts as valid or invalid would be left up to you, so you could always return a `200` but return an errors JSON object if the field was invalid.

**Comment by senseluo** [comment]
highly need custom response feature

**Comment by darknest** [comment]
I just copy-paste the example here in github

`      <form data-toggle="validator">
        <div class="form-group">
          <label class="control-label" for="remoteValidator">Best Food:</label>
          <input type="text" name="username" id="remoteValidator" class="form-control" data-remote="/registrazione/checkUsername">
           <div class="help-block with-errors">Hint: 'pizza'</div>
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>

      </form>`

This is the form

`if($trovaUsername){
			header('HTTP/1.1 404 Not Found');
		}else{
			header("HTTP/1.1 200 OK");
		}`

This is the PHP where I pass the error.  It wont put the 404 Not Found in the "**<div class="help-block with-errors"></div>**"...

Any suggestions?
