### ISSUE TITLE
Form in modal with datatable in the same page

### ISSUE THREAD

**Issue by amaurydixx** [1000hz/bootstrap-validator#411]
Hello;

On my website, I put a datatable and, in each line, a button to edit the data.
The button opens a modal with a form who contains the appropriated data.
The problem is that the form is always valid. Even if there is an error.

If i delete the datatable (I keep the button to open the modal), everything works fine.

Any idea?

**Comment by 1000hz** [comment]
You probably aren't initializing the validator. Be sure you call `$('#myForm').validator()` once the modal is displayed on the page (not just at page load)

**Comment by amaurydixx** [comment]
Hello;

Thank you for the answer.

I use this script. It is called just before the form.

<script id="jsbin-javascript">
//Script de validation du formulaire dans le modal (modification d'un contact)
$('#responsive-modal')
  .on('shown.bs.modal', function (e) {
    $('#modcontact').validator()
  })
  .on('hidden.bs.modal', function (e) {
    $('#modcontact').validator('destroy')
  })
</script> 

If I delete the datatable on the page, the validator works perfectly.
If the datable is on the page (the trigger which call the modal is a button in a datatable line), the validator always validate the form. Even if there is an error!

I think it is a bad interaction with datatable.

**Comment by 1000hz** [comment]
If you're using `data-togle="validator" to initialize the plugin, it won't work because that only runs at page load, and I'm assuming your form isn't actually in the DOM yet. You need to initialize the plugin _after_ your form is in the DOM, so you need to initialize it via JS with `$('#myForm').validator()`. Also, be sure you're using the latest version of the plugin, because earlier versions didn't validate inputs that weren't visible on the page which caused a lot of problems with forms inside of modals.
