### ISSUE TITLE
How to check email id already exists using bootstrap-validator

### ISSUE THREAD

**Issue by GNSubrahmanyam** [1000hz/bootstrap-validator#412]
How to check email id already exists using bootstrap-validator with AJAX & PHP.

**Comment by 1000hz** [comment]
Use the `data-remote` validator to talk to your backend. Check the docs for a link to a reference implementation written with an express server in node. If you need more help, please post a question on StackOverflow.

**Comment by GNSubrahmanyam** [comment]
can you give some example

**Comment by 1000hz** [comment]
http://1000hz.github.io/bootstrap-validator/#validator-markup
>- `data-remote="/path/to/remote/validator"` to make an AJAX request to determine if the field is valid or not. Be sure to give the input a name attribute, as the request will be sent to `/path/to/remote/validator?<name>=<value>`. The remote endpoint should return a `200 OK` if the field is valid, and a `4xx` otherwise. Here's a [reference server implementation](https://github.com/1000hz/validator-remote-example) using Express.

**Comment by chrisribe** [comment]
Hi,

There seems to be an issue with encoding and server returned error messages.
In my case the error messages are in french, and since the message must be in the header ex: "4xx this email taken" the result is garbled...

I tried using the custom option but am unable to return the error message since the operation is async.
Any ideas / tips ?
