### ISSUE TITLE
problem to show validations when fields are readonly

### ISSUE THREAD

**Issue by amaganon** [1000hz/bootstrap-validator#416]
The validator works and highlights the fields properly when the fields are in normal mode. But by placing readonly fields and fill them with from java escripts fields validations fail to show despite not having correct or appropriate values.

Appreciate if someone can tell me how to correct this detail , I am new to using bootstrap and jquery and I'm not even able to edit or correct such details.

Thank you in advance for your help. Goodnight
![problem](https://cloud.githubusercontent.com/assets/22308778/18653818/88dc3eb4-7eaa-11e6-8ee9-71734cf565ee.png)

**Comment by nelson6e65** [comment]
If they are `readonly`, the user can't fix it! So, it has not sense notify the user, because is not "setting" any wrong value in that fields.

**Comment by 1000hz** [comment]
If a field is marked `readonly` or `disabled`, the browser assumes the field is valid (`element.checkValidity() == true`). This means the plugin has no way of running built-in validators for these fields.

You can work around it by adding a custom validator that momentarily enables the field in order to run its validators and then restores the read-only state and returns any errors.
http://jsbin.com/qadugiwudi/edit?html,js,output
