### ISSUE TITLE
Perfect full email validation

### ISSUE THREAD

**Issue by 74644p** [1000hz/bootstrap-validator#455]
Thanks for the wonderful validation. I cannot express how helpful this has been to me...

I have a small suggestion. While working with email field: 
email is considered valid once a character comes after "@" symbol.
i.e.: if i assign " **test@g** " email is valid. 

It would have been better to make it as valid once  below points are valid : 
 - at least 2 characters after "**@**" symbol ( e.g: someone@**do**)
 - followed by at lest 1 **" . "** / (period) ( e.g: someone@mail. ) 
 - & at least 2 character after the period. ( e.g: someone@mail.**us**)

Thanks and enjoy life..

**Comment by 1000hz** [comment]
Hi, thanks for the kind words! This has been brought up a few times before (#272, #31) and according to the [W3C spec that defines valid email addresses](http://w3c.github.io/html/sec-forms.html#valid-e-mail-address), `test@g` is valid. This plugin uses built-in browser APIs to handle email address validation, and the browsers implement it according to that spec.

If you would like to validate against something more strict than the spec, you can combine the `type="email"` validator with the `pattern` validator. Personally, I'd advise against it because you risk making a frustrating user experience for someone who has a strange but legal email address (though admittedly it would a rare case). For reference, you could use:
```html
<input type="email" pattern=".*@\w{2,}\.\w{2,}" class="form-control">
```
to implement the rules you specified above.

**Comment by 74644p** [comment]
thanks for the quick and valuable response.

**Comment by Silvestarserpentcs** [comment]
How can we validate only corporate mails not from gmail.com, yahoo.com, outlook.com
eg : username@github.com

**Comment by 1000hz** [comment]
@Silvestarserpentcs you could use a custom validator
