### ISSUE TITLE
Set "required" atribute in others fields by other changed

### ISSUE THREAD

**Issue by cajobao** [1000hz/bootstrap-validator#458]
Hi guys, in first place apologize my english and if this issue as exist's.
I have a condition that I need to make other fields mandatory from the other fill.
In this case, I put the 'required' attributes via javascript in these fields. And I need that at that moment that group of fields that depend on this, are validated.
```
	function habilitaObrigatoriedadeRg() {
		if ($('#nr_rg').val().length > 0) {
	        $("#dt_emissao_rg").attr('required','');
	        $("#orgao-expedidor").attr('required','');
	        $("#uf_rg").attr('required','');
		} else {
	        $("#dt_emissao_rg").removeAttr('required');
	        $("#orgao-expedidor").removeAttr('required');
	        $("#uf_rg").removeAttr('required');
		}
	}
```
how i do this?

**Comment by rhedman** [comment]
I'm pretty sure you should use .prop() and not .attr()

prop("required", true);

**Comment by cajobao** [comment]
> rhedman commented 28 minutes ago • edited
> I'm pretty sure you should use .prop() and not .attr()
> 
> .prop("required", true);

My ways works. What a need is start a validation on this fields in this function.

**Comment by rhedman** [comment]
From the documentation

"By default, the validator will only validate fields that are present when the plugin is initialized. If your form has a dynamic set of fields, you will need to call $(...).validator('update') to inform the plugin that the set of fields to be validated has changed."

**Comment by cajobao** [comment]
Yes, but this work's for all form.
I need that if change a field, others fields (a group of then) are validate or non validate if this field are blank.

**Comment by 1000hz** [comment]
`.validator('update')` is only necessary if new fields are added / removed from the DOM. Toggling attributes on inputs already in the DOM won't require an update since those inputs are already in the validator's jQuery selection.

@rhedman is right in that you probably want to use `.prop()` instead of `.attr()`. I think jQuery v1.x automatically updated the element's internal property, but in jQuery 3.x this is no longer the case.

Also, you can trigger validation on a field with `$('...').trigger('focusout')`.

I'd rewrite your function as

```js
function habilitaObrigatoriedadeRg() {
  $('#dt_emissao_rg, #orgao-expedidor, #uf_rg')
    .prop('required', !!$('#nr_rg').val().length) // are you sure you want to call .length on .val()?
    .trigger('focusout')
}
```

**Comment by cajobao** [comment]
Thank's a lot.
