### ISSUE TITLE
Issues Understanding Methods (Form in Fieldsets with Next Button)

### ISSUE THREAD

**Issue by acignarella3** [1000hz/bootstrap-validator#474]
The form that I am trying to validate is contained in a series of fieldsets connected by next and previous buttons. Rather than hinge all of the validation on an ending submit button, I want to call the validator each time the next button is clicked, so that it checks everything currently on the page and only allows the user to proceed if everything is valid.

I understand from the documentation that the .validator('update') method can be used for a dynamic set of fields, which I assume my form qualifies as. However, I am struggling to understand and thus properly utilize the methods listed. Would it suffice just to call .validator('update') followed by .validator()? Would .validator('validate') be more relevant? Do any of these methods output a value such as a boolean that could be of use? Does Bootstrap Validator even work on anything other than a button of submit type?

Any help clarifying any of these issues would be greatly appreciated. Thank you.

**Comment by 1000hz** [comment]
Yes, you would need to use `.validator('update'). You only need to call `.validator()` once to initialize the plugin. `.validator('validate') is used if you want to trigger a full form validation programmatically (instead of waiting for submit). All of these methods return the jQuery collection they are operating on. The plugin only validates automatically for submit buttons, but you can prevent the submit event and show the next page of the form if you don't want to submit to the server yet.

Closing the issue, but feel free to ask follow up questions.

**Comment by acignarella3** [comment]
So here's the dilemma I'm seeing: You recommend using `.preventDefault()` to allow a submit button to move to the next fieldset rather than submitting the form there and then. However, the documentation says `.preventDefault()` is used when the form is invalid, and recommends using `.isDefaultPrevented()` as a custom check. Can Bootstrap Validator allow your recommended change on the submit buttons while still being able to checking for form validity?

**Comment by 1000hz** [comment]
if the form is invalid, `e.preventDefault()` will have already been called. If it IS valid, you'll still need to call `e.preventDefault()` to stop the form from being submitted to the server.

something like...
```js
$('form').on('submit', function (e) {
  if (!e.isDefaultPrevented() && formPage == LAST_PAGE) {
    e.preventDefault()
    showNextFormPage()
  }
})

**Comment by acignarella3** [comment]
Been playing around with it on this one example I found online, especially with adding the suggestions you made, and I'm having one main issue: `e.isDefaultPrevented()` always returns true, even if the current form is valid (i.e. no error messages).

The code particularly wraps the functions inside `$(document).ready(function() {...});`. I've tried commenting that out, and it results in the opposite problem, with `e.isDefaultPrevented()` always returning false even if the form is invalid.

I'm bringing this up because I'm trying to get a better sense of how to properly debug the validator on submit, if I even can. I'm also curious if you (or anyone else) have come across this sort of issue before.

**Comment by 1000hz** [comment]
Your submit handler needs to be bound after the plugin has been initialized. This is because jQuery fires event handlers in the order they were bound, so if you bind your submit handler before initializing the plugin it wouldn't yet have called `e.preventDefault()`. I'm not sure why `e.isDefaultPrevented()` is always returning true for you in the first case (might be something else preventing default).

In the future there will be a more reliable way to determine if the form is invalid, probably using the built-in `formElement.checkValidity()` method (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement). This will come with #450.
