### ISSUE TITLE
textarea pattern regexp

### ISSUE THREAD

**Issue by rudzikdawid** [1000hz/bootstrap-validator#51]
Are there any chance to add support for textarea regex validation?
html5 does not support pattern attribute in textarea element
but maybe, this plugin will be able to?

**Comment by 1000hz** [comment]
No, since I'm piggy-backing off of HTML5 validation, there won't be any official support for textarea regex validation, but you can add a custom function validator that will run your regex like this:
https://github.com/1000hz/bootstrap-validator/issues/20#issuecomment-44555179

In the next release, I'll probably add support into the API for custom validator functions, but this should solve your problem in the mean time.

**Comment by rudzikdawid** [comment]
thanks for help. Now regex validation on textarea working like charm

js:
```
Validator.VALIDATORS.pattern = function ($el) {
        var patternRegExp = $el.data('pattern');
        return $el.val().match(eval(patternRegExp));
    }
```
html:
```
<textarea class="form-control" cols="20" data-error="error" data-pattern="/regex_here/g" data-pattern-error="error_text" name="name" placeholder="place_text" required="required" rows="5"></textarea>
```

**Comment by aryac** [comment]
i'm beginner with bootstrap, need more help on this for textarea validation.

**Comment by adriennn** [comment]
@aryac what you can do is to edit the source of the plugin and add the error text for pattern matching:
```javascript
  Validator.DEFAULTS = {
    delay: 500,
    html: false,
    disable: true,
    custom: {},
    errors: {
      match: 'Does not match',
      minlength: 'Not long enough',
      pattern: 'Illegal characters'
    }
  }
```
and then add the method (prefer `new regExp()` in `Validator.VALIDATORS`:
```javascript
  Validator.VALIDATORS = {
    'native': function ($el) {
      var el = $el[0]
      return el.checkValidity ? el.checkValidity() : true
    },
    'match': function ($el) {
      var target = $el.data('match')
      return !$el.val() || $el.val() === $(target).val()
    },
    'minlength': function ($el) {
      var minlength = $el.data('minlength')
      return !$el.val() || $el.val().length >= minlength
    },
    'pattern': function ($el) {
      var pattern = $el.data('pattern')
      return !$el.val() || new RegExp(pattern,"g").test($el.val())
    }
  }
```
Then in you `<textarea>` add

```html
data-pattern="your regex"
```

This works  but it is not an encouragement to do user input filtering/sanitizing in the frontend.

**Comment by 1000hz** [comment]
You don't need to edit the source code of the plugin* since custom validators are now supported via the API. Pass the validator and error in as options when you initialize the validator.

```js
$('#myForm').validator({
  custom: {
    pattern: function ($el) {
      var pattern = $el.data('pattern')
      return !$el.val() || new RegExp(pattern,"g").test($el.val())
    }
  },
  errors: {
    pattern: "Illegal characters"
  }
})
```
    
---
_*Even before custom validators were fully supported, the preferred way to accomplish what you're suggesting would have been to add the extra validator and error at runtime inside of your own script instead of modifying the source of the plugin directly since doing so would make future upgrades harder._
```js
$.fn.validator.Constructor.VALIDATORS.pattern = function (e) {...}
$.fn.validator.Constructor.DEFAULTS.errors.pattern = "..."
```
