### ISSUE TITLE
pattern validation message

### ISSUE THREAD

**Issue by drosendo** [1000hz/bootstrap-validator#53]
FYI,

Added a validation message for pattern, dont know if it's best approach.

```
  if (key == 'native' && typeof $el.attr('pattern') !== typeof undefined)
                    key = 'pattern';
```

Now i can run
```
 $('form').validator({
                delay: 500,
                html: false,
                errors: {
                    pattern: "Not valid pattern",
                    match: 'Dont match',
                    minlength: 'lalalala'
                }
            });
```

At least this method can be applied to more attributes...

Wait for feedback.

**Comment by 1000hz** [comment]
If the only validation you need on this field is the pattern validator, you can just add a `data-error="Please match the requested format"`, but if you also want a different message for something like the `required` validator, you will run into problems. In that case, you'd need to do something like you did above.

The plugin depends on the HTML5 Constraint Validation API in order to stay lean and simple, but the downside of this is the problem you're running into.

**Comment by drosendo** [comment]
That is exactly why i did this...

Great work anyway :)

**Comment by cbterceiro** [comment]
drosendo, where did you insert those bits of code? I would like to have this too. Thanks

**Comment by drosendo** [comment]
HI,

Line 129 to 134

This
```javascript
$.each(Validator.VALIDATORS, $.proxy(function (key, validator) {
    if (($el.data(key) || key == 'native') && !validator.call(this, $el)) {
        var error = getErrorMessage(key)
        !~errors.indexOf(error) && errors.push(error)
    }
}, this))
```
to this:

```javascript
$.each(Validator.VALIDATORS, $.proxy(function (key, validator) {
    if (($el.data(key) || key == 'native') && !validator.call(this, $el)) {
        if (key == 'native' && typeof $el.attr('pattern') !== typeof undefined)
            key = 'pattern';
        var error = getErrorMessage(key)
        !~errors.indexOf(error) && errors.push(error)
    }
}, this))
```

**Comment by cbterceiro** [comment]
Thanks :)
