### ISSUE TITLE
Validation of passwords not working if both password fields are not required...

### ISSUE THREAD

**Issue by fedeolivera1** [1000hz/bootstrap-validator#582]
Tried directly from the source: 
http://1000hz.github.io/bootstrap-validator/?underwear=on
removing the required attribute on both password fields.
If "required" attribute is taken off (not present on both inputs), the second password field will not validate if you leave it blank, of unfilled, and the first password field completed.
Is this a bug?

**Comment by fedeolivera1** [comment]
Anyone can give an idea here? Is this happening to someone else?

**Comment by 1000hz** [comment]
If I correctly understand what you're asking, this is how the validator is designed to work. Any input that's not marked `required` will not be invalid if it's blank. So your second password field isn't invalid even though it doesn't match because providing a value for that field is considered optional.

It sounds like the behavior that you want is for the second password field to be required only if the first password has a value. You can accomplish this by toggling the `required` attribute on the second password anytime the first input changes. See this example:
http://jsbin.com/xugetigabe/edit?html,js,output

**Comment by fedeolivera1** [comment]
Hey man!!! That was EXACTLY what I needed thank you!!!!!!. I'm sorry to
have opened an issue that were not an issue, and I appreciate very much
your help. Your validator is simply awesome, even tough I'm just starting
to use it and I know very little about bootstrap and UI.
Thank you again man, cheers!

2017-08-23 11:33 GMT-03:00 Cina Saffary <notifications@github.com>:

**Comment by 1000hz** [comment]
glad to help!
