### ISSUE TITLE
Response from .validator('validate')

### ISSUE THREAD

**Issue by cpede** [1000hz/bootstrap-validator#69]
I'm totally new to jQuery and your Validator, so maybe my question is stupid?

I want to pragmatically validate my form. This works, but I want to know if the validation failed or succeeded.

var b = $('form[name="myform"]').validator('validate'); // VALIDATES MYFORM
if (b == false) alert("false"); // NOT WORKING

Can I use the return value "b" is some way to determine that?

Also can I set focus on the field that fails the validation?

-cpede

**Comment by 1000hz** [comment]
There's a convention for jQuery methods to return another jQuery object to allow you to chain method calls together on the same set of selected elements, so `b` in your example would be a jQuery object.

The validator docs list a method to check if the form is valid upon it being submitted, but since you're not submitting the form, you can check if any fields have the class `.has-error` on them.

```javascript
var hasErrors = $('form[name="myform"]').validator('validate').has('.has-error').length
if (hasErrors) alert('false')
```

**Comment by ptica** [comment]
:+1: 
could this be mentioned in the docs?

**Comment by ptica** [comment]
I think
```js
var hasErrors = $('form[name="myform"]').validator('validate').has('.has-error').length
if (hasErrors) alert('false')``
```
has a time race issue, see #116
