### ISSUE TITLE
Error Summary (at top)

### ISSUE THREAD

**Issue by chenrycommit** [1000hz/bootstrap-validator#76]
Is it possible to list a consolidated error summary in one place, instead of independent errors for each form-group?   I'm building a mobile app and vertical space is critical for good UX.  I'd like to highlight all of the error fields in red and then slide down a dismissible error summary on a layer above the form view.

**Comment by 1000hz** [comment]
Hook the `invalid.bs.validator` event and pull the errors out of `$(e.relatedTarget).data('errors.bs.validator')` and put them where you need to. Don't forget to hook the `valid.bs.validator` event too to clean the errors up when they get fixed.

**Comment by chenrycommit** [comment]
Thanks!  Any chance you could post a code snippet for this?  Much appreciated!

**Comment by 1000hz** [comment]
You could actually use `e.detail` for the errors instead of pulling it off the data object. I forgot I surfaced that in the event object.

Here's a rough code snippet, but the user experience is bad because the events fire immediately and don't give the user any chance to type a valid input before raising an error message. You'll need to implement debouncing the message. In a future release I'll add another pair of events that are fired after the error message is shown (after the delay period).

Anyways, with that caveat: http://jsbin.com/ziqaqefami/1/edit?html,js,output

**Comment by pani100** [comment]
Thanks,
 this worked fine for normal inputs. For array inputs it can't find the data-name of the array. Need to double quote the data-name value like:

var $errors = $('#errors')
    
$('form[data-toggle="validator"]')
  .on('invalid.bs.validator', function (e) {
    var $field = $(e.relatedTarget)
    var errors = e.detail
   
    var $errorsList = $('<ul/>').attr('data-name', $field.attr('name'))
    $errorsList.append($.map(errors, function (error) {
      return $('<li/>').text(error)
    }))
    
    $errors.find('ul[data-name="' + $field.attr('name') + '"]').remove()
    $errors.attr('hidden', false).append($errorsList)
    $errors.append($errorsList)
  })
  .on('valid.bs.validator', function (e) {
    var $field = $(e.relatedTarget)
    $errors.find('ul[data-name="' + $field.attr('name') + '"]').remove()
    $errors.find('ul').length || $errors.attr('hidden', true)
  })
