### ISSUE TITLE
Accents are broken when returning the http response

### ISSUE THREAD

**Issue by vicentor** [1000hz/bootstrap-validator#88]
It seems like the renderer escapes html entities so I think it's possible to return accent characters through an error message. &eacute; is litterally shown.
`header("HTTP/1.1 409 Ce nom d'utilisateur est déjà en utilisation.", true, 409);`

**Comment by 1000hz** [comment]
I'm not sure I understand what the issue is. Can you elaborate?

UTF-8 characters are being displayed unchanged when returned in the response for a remote validator. That seems like what you'd want to happen... right?

If what you're trying to say is that the php header function is escaping your accent marks before it sends the response, then that's an issue not in the scope of this library.

**Comment by vicentor** [comment]
It's the resulting javascript that returns weird characters instead of accents, I will investigate furthermore because it could be a server-side issue. If on the server the accent is not broken due to encoding and it only gets destroyed through the library, I'll reopen this.

Thank you for answering! :)
